### ISSUE TITLE
what is expected flow for the network nodes?

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/vdc#15]
with no public IPs at the moment, what is expected flow for the network nodes?
deploy a node on DO per VDC? or how will the cluster is exposed

_Originally posted by @m-motawea in https://github.com/threefoldtech/home/issues/949#issuecomment-726052773_

**Comment by m-motawea** [comment]
in case of DO, we need to upgrade the project to cover more vms as there will be a VM for each deployed VDC

**Comment by xmonader** [comment]
quoting @despiegk  deploying VMs over DO isn't an option anymore.
