### ISSUE TITLE
s3 domain names

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/vdc#17]
how is s3 going to be exposed?
options:
1- public IP (no valid cert)
2- expose using gateway (managed domains)

note aws uses this for s3 urls:
`https://s3.Region.amazonaws.com/bucket-name/key name`

**Comment by robvanmieghem** [comment]
A lot of S3 clients do not even work without valid https

**Comment by robvanmieghem** [comment]
Does the s3 have to exposed publicly directly or to the kubernetes pods?

**Comment by robvanmieghem** [comment]
I rephrased the last comment in a seperate question: Exposure of the S3 #40
