### ISSUE TITLE
s3 topup

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/vdc#19]
s3 auto-top up, should extend once 70% is reached. [don't bother with authentication ](https://github.com/threefoldtech/minio/issues/123)

related issues

- https://github.com/threefoldtech/minio/issues/124
- https://github.com/threefoldtech/minio/issues/123
- https://github.com/threefoldtech/minio/issues/122

**Comment by m-motawea** [comment]
when it reaches 70% how much capacity should it add? or make it go down to how much percent?

**Comment by xmonader** [comment]
> when it reaches 70% how much capacity should it add? or make it go down to how much percent?

let's make it configurable, but i think increase with 100GB (or whatever remaining in the package when less than 100GB) is ok

**Comment by m-motawea** [comment]
auto topup service is part of tfgrid_solutions and runs every 2 hours

example config:

```python
JS-NG> j.core.config.get("S3_AUTO_TOP_SOLUTIONS")                                                                                                                                                                  
{'farm_names': ['freefarm'], 'extension_size': 3, 'max_storage': 30, 'threshold': 0.7, 'clear_threshold': 0.4, 'targets': {'testpub': {'minio_api_url': 'http://172.30.3.2:9000', 'healing_url': 'http://172.30.3.2:9010'}}}
```
