### ISSUE TITLE
Marketplace UI for deploying helm charts

### ISSUE THREAD

**Issue by AhmedSa-mir** [threefoldtech/vdc#24]
#### Frontend:
- [x] Select VDC **_[NO LONGER NEEDED IN NEW FLOW, only one VDC per MARKETPLACE]_**
- [x] Replace usage of expose with public IPs 
- [x] Each helm chart should have an installation button that directs to its chatflow
- [x] list all installed charts
- [x] Delete/uninstall existing chart

#### Backend:
- [X] - Base chatflow with common chatflow steps for all helm chart installations
- [X] Install chart on existing vdc
- [X] Expose domain on the k8s cluster
- [X] - Check flow:
   * (option 1) expose -> install chart with params **[OPTION CHOSEN]**
   * (option 2) install chart -> expose domain -> set values.yaml and apply ingress file

Suggested flow for listing:
- Sidebar with [New Charts, Existing VDC Charts]
- New charts will include all the solutions, where each directs to its chatflow which includes selecting the vdc to install tht chart on
- Existing VDc Charts will include overviews on charts already installed on each selected vdc and option to delete/uninstall
- This approach is suggested to avoid looping on all the existing vdc to list their installed charts, but instead only check the charts installed on one vdc selected per time

**Comment by ranatrk** [comment]
Updates: https://github.com/threefoldtech/js-sdk/commit/d602a230ac3b063b6d289fe095e35810ced1a814
- Add base vdc solutions chatflow.
- Add vdc cryptpad solution.
- Add maketplacevdc chatflow docs.

**Comment by ranatrk** [comment]
Flow:
- List chart options--> Each with DEPLOY(link to chatflow) & MY WORKLOADS(link to solutions view) buttons
- **(DEPLOY)** Chatflow -->  list vdcs--> select vdc,get tname --> get kube.conf --> using kube.conf install chart on vdc k8s cluster with namespace as the solution type(eg: namespace="cryptpad") for future filtering
- **(MY WORKLOADS)** Solutions view(For each specific solution):
  - List all vdcs --> get vdc name,tname --> config path --> kube.conf
  - For each kube.conf--> list all releases with specific filter (chart namespace added when installing the chart)
  - Merge each k8s cluster releases result in a list/dict and return to frontend to view in solution table

**Comment by ranatrk** [comment]
**Progress:**
- Select vdc from chatflow in a step and use config, master ip..etc from the vdc instance installed
- Removed hard coded vdc values
- Added wait for deployment of chart success in step `initialization`
- Fix frontend APIs (install, delete charts) to allign with listing of available VDCs

**Changes:**
https://github.com/threefoldtech/js-sdk/commit/9e9e5f019baceced657873fe7df1c806e70aab46
https://github.com/threefoldtech/js-sdk/commit/fc9b107f8928ba5519048d5677a1393bcd8c070e
https://github.com/threefoldtech/js-sdk/commit/cbb699c6f7e486729837c080cae56c9bd9c58e7b
https://github.com/threefoldtech/js-sdk/commit/c42ddbb1aa8751839100aba7d54d8bc03b07fb11

**Comment by xmonader** [comment]
One last update to this story

- there will be no central marketplace, the package will be installed on the vdc 3bot, and the 3bot will have the kubeconfig ready and all of the vdc identity information in the 3bot itself ready, no need to list vdcs for deployment, it will be the configured identity
