### ISSUE TITLE
Investigate why traefik is not working with current charts

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/vdc#28]
currently traefik doesn't work we are using nginx controllet instead with

```
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm install my-release ingress-nginx/ingress-nginx
```

**Comment by OmarElawady** [comment]
This was fixed by modifying the annotations to use traefik instead of nginx
https://github.com/threefoldtech/marketplace-charts/commit/e3e9cbf7769723b27199a6151836bed2c459607d
