### ISSUE TITLE
Use kubernetes tools like kubectl to access our VDC without wireguard

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/vdc#30]

**Comment by robvanmieghem** [comment]
Having a control plane seems secure to me, can't we use kubectl over wireguard?

**Comment by xmonader** [comment]
> Having a control plane seems secure to me, can't we use kubectl over wireguard?

I believe this is coming from mac issue to use only 1 wireguard config

**Comment by m-motawea** [comment]
the plan is to give the user kube config to be used with kubectl over public ip. the user won't have access to wireguard

**Comment by xmonader** [comment]
accessible using the public ip
