### ISSUE TITLE
taiga chart

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/vdc#34]
child of https://github.com/threefoldtech/vdc/issues/12

**Comment by OmarElawady** [comment]
Taiga added [here](https://github.com/threefoldtech/marketplace-charts/commit/06ffbae6558e3d15ea60697d14d455698758f66f):

- Currently the taiga operates on http, it can be used over http or exposed using a reverse proxy that provides SSL functionality and forwards the traffic to port 80 to the ingress.
- Resources/limits are not set yet, but the pod fails to initialize on 2G ram k3s's, and it works on 4G.

**Comment by OmarElawady** [comment]
Resources and limits are now set to 1G memory. Maybe it was failing because of early failures of liveness probes (delay is added).

**Comment by dmahmouali** [comment]
Verified on testnet VDC.

![image](https://user-images.githubusercontent.com/36021484/102803399-da4a0d00-43c0-11eb-8d42-4a489ddc460c.png)
![image](https://user-images.githubusercontent.com/36021484/102803415-e03fee00-43c0-11eb-9074-d1cdeaabc821.png)
![image](https://user-images.githubusercontent.com/36021484/102803451-ee8e0a00-43c0-11eb-83fd-2058f6e9c214.png)
![image](https://user-images.githubusercontent.com/36021484/102803522-09607e80-43c1-11eb-84b3-fe098cf8db27.png)
![image](https://user-images.githubusercontent.com/36021484/102803622-2dbc5b00-43c1-11eb-96ee-b172c022030b.png)
![image](https://user-images.githubusercontent.com/36021484/102803814-84299980-43c1-11eb-99d2-ca636810c28a.png)
![image](https://user-images.githubusercontent.com/36021484/102803829-8be93e00-43c1-11eb-8724-d6e8d552eab8.png)
![image](https://user-images.githubusercontent.com/36021484/102803846-94417900-43c1-11eb-95e2-c360ec8d5529.png)
