### ISSUE TITLE
peertube chart

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/vdc#35]
part of https://github.com/threefoldtech/vdc/issues/12

**Comment by OmarElawady** [comment]
The peertube chart is added [here](https://github.com/threefoldtech/marketplace-charts/tree/master/charts/peertube).
It makes 3 pods with the following resources/limits constrains:
- postgres:  Memory: 256Mi, CPU: 250m
- redis:        Memory: 256Mi, CPU: 100m
- peertube: Memory: 1024Mi, CPU: 1000m
The volume provisioned by rancher k3s is local which means it's mounted on the node. Maybe [loghorn](https://rancher.com/products/longhorn/) is a better option?

**Comment by dmahmouali** [comment]
While verification, I can upload videos but can't play the video

![image](https://user-images.githubusercontent.com/36021484/102800751-f77cdc80-43bc-11eb-9ca2-3d6f1e083622.png)
![image](https://user-images.githubusercontent.com/36021484/102801191-87bb2180-43bd-11eb-8c1b-7f6f9a8bb6be.png)
![image](https://user-images.githubusercontent.com/36021484/102801404-dc5e9c80-43bd-11eb-8203-a7aefe515b6d.png)

**Comment by OmarElawady** [comment]
The chart was served over http, so it can't be accessed over https (the frontend can't fetch resources over different protocols for security reasons). I changed the protocol to https, and disabled the certificate config in this [commit](https://github.com/threefoldtech/vdc-solutions-charts/commit/49298c8f5d2277527ea561f395f90a14b7f82857).
