### ISSUE TITLE
gitea chart

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/vdc#37]
part of part of https://github.com/threefoldtech/vdc/issues/12

**Comment by dmahmouali** [comment]
Verified.

![image](https://user-images.githubusercontent.com/36021484/102800004-f0a19a00-43bb-11eb-8af4-eb9f6e3c89c3.png)
![image](https://user-images.githubusercontent.com/36021484/102800158-247cbf80-43bc-11eb-9d62-e2a3519bd6dc.png)
![image](https://user-images.githubusercontent.com/36021484/102800040-00b97980-43bc-11eb-8f17-26fecf4e862f.png)
![image](https://user-images.githubusercontent.com/36021484/102800116-14fd7680-43bc-11eb-8ff6-99a5904e0f43.png)
![image](https://user-images.githubusercontent.com/36021484/102800192-3199ae80-43bc-11eb-99d9-b2b65911dec6.png)
![image](https://user-images.githubusercontent.com/36021484/102800215-3c544380-43bc-11eb-903e-6751a22abeab.png)
