### ISSUE TITLE
Exposure of the S3

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/vdc#40]
For the MVP, should the S3 be exposed  only to the kubernetes cluster in the vdc or also be accessible  publicly?

Having it accessible publicly has some consequences:
- security
- domain names
- ssl certificates

While S3 is mainly storage  for applications, exposure inside the vdc might be sufficient

**Comment by xmonader** [comment]
We need to be able to monitor and to reach that so two cases
1- we be part of the same private network of the s3
2- we reach it over public ip

note: containers can't be part of multiple networks  https://github.com/threefoldtech/zos/issues/979

**Comment by despiegk** [comment]
why do we monitor S3 usage?
can't we do it on ZDB level, which is maintained by the user 3bot?

**Comment by xmonader** [comment]
> why do we monitor S3 usage?
> can't we do it on ZDB level, which is maintained by the user 3bot?

we can't do ip4(k8s) user3bot to public ip6 zdb, that's why minio is deployed on a separate container on the grid. please check this document 
https://github.com/threefoldtech/vdc/blob/main/docs/architecture.md

![image](https://user-images.githubusercontent.com/64129/99794739-5091f000-2b33-11eb-98f5-289974f064a5.png)

**Comment by robvanmieghem** [comment]
So this means that the admin interface of minio is also publicly exposed and the minio S3 interface is deployed inside the vdc right?

**Comment by xmonader** [comment]
> So this means that the admin interface of minio is also publicly exposed and the minio S3 interface is deployed inside the vdc?

the calls to the non authenticated endpoints over the public network can be intercepted in the ingress
