### ISSUE TITLE
deploying s3 frontend (minio) in k8s cluster

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/vdc#45]
check if possible to run minio with in the k8s cluster

**Comment by m-motawea** [comment]
ZDB use IPv6, and minio container requires IPv6 to be able to access it. 
currently, kubernetes doesn't support IPv6, so no containers deployed on it would be able to communicate with ZDB

**Comment by xmonader** [comment]
@m-motawea thanks, the architecture file updated to reflect that already https://github.com/threefoldtech/vdc/blob/main/docs/architecture.md

**Comment by zaibon** [comment]
0-OS managed to get dual stack in the K8S VM. But it seems K8S networking itself is not going to be that easy to get to work with IPv6. So for now let's keep the minio in a 0-OS container. Maybe in a later version we could move it into the cluster.

**Comment by rkhamis** [comment]
dropped
