### ISSUE TITLE
Create helm chart for zeroci

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/vdc#46]
### Description

For easier deployment and maintenance we need to deploy zeroci using helm
something like this can help 
https://bitnami.com/stack/jenkins/helm

**Comment by AhmedHanafy725** [comment]
#### How to install
```bash
helm install mytest marketplace/zeroci --namespace myspace --create-namespace --set "ingress.hosts[0].host=testzeroci.tfgw-testnet-01.gateway.tf" --set "ingress.hosts[0].paths[0]=/"
```
If there is more than one instance, it should be installed with different volumes paths for `bin`, `redis`, and `persistent`

**Comment by xmonader** [comment]
verified
