### ISSUE TITLE
Monitor 3bot with Grafana

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/vdc#48]
We want to visualize logs, alerts, and heartbeats of 3bot on Grafana  to facilitate maintenance and support

#### steps
- [ ] Make 3bot configurable to push logs, alerts, and heartbeats to a remote machine.
- [ ] Create an endpoint on the remote machine to authenticate the requests.
- [ ] Save the logs and alerts in Redis
- [ ] Use Grafana to pull from Redis and visualize the data

**Comment by zaibon** [comment]
Redis is not a database you can use to **store** the logs. Redis is just used by 0-OS as a pubsub/queue system.
What needs to happens is you have a process on the monitoring machine that subscribe to the redis channel and copy the logs into a database.
The log aggregation tools you use can then read from the database.
Be aware that redis pubsub has not backlog system, so if your process is not reading the logs from redis, these logs will just be lost.

**Comment by RafyAmgadBenjamin** [comment]
- For Logs
We have used `Loguru` to send the logs from the 3bot(client) to another machine (server) by adding a new handler, then we will store this data in `Influxdb` to be fetched by `Grafana` later on

**Comment by xmonader** [comment]
verified, been demoed multiple times too.
