### ISSUE TITLE
billing flow

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/vdc#5]
the user will be reserving a k8s cluster with their own money and it will be consuming CUs/SUs already, to charge per usage per day this means double charging or we want to make extra money out of this? so we pay for the minimum and keep charging for usage?

**Comment by gmachtel** [comment]
If I understood well, user pays an all-in fee. If no consumption we win on it, if it's used a lot we might win less or even lose on it. But for getting traction, I understood this is acceptable. So no, no extra charging.

**Comment by rkhamis** [comment]
a few questions regarding the billing:

- if a user is being charged for the entire solution plan they used, why are we not making it available right away? the user will then see in their dashboard something different than what they paid for.

 - the daily charging: is this for s3 and kubernetes usage? or for marketplace deployments? is it then per resource usage? or per deployment?

 - if a user doesn't consume their plan, should they be refunded or should it be carried over? or do we still charge it?

**Comment by despiegk** [comment]
they are charged for what they have deployed (in CU/SU)
we need to know max used per day
each day we charge for what they used
any resources used in VDC counts

its only post usage, so don't understand remark

the plan is the base, which they always pay, if less than plan no refund
if more than plan we charge,

**Comment by gmachtel** [comment]
Base/subscription amount : OK, also fact that there is no refund if consumption with the farmers is less than what has been subscribed for. 
For the post usage payment, I propose to leave it out of the MVP, as for post usage there is also complexity that the user needs to sign for the payment (we can't take it from his wallet ourselves). Flow becomes more complex, can't we simply state that when all is consumed, we stop the provisioning? Or, for now, if not possible to do so, accept that we loose a bit on it. Needs monitoring of course as first step, there I agree.

**Comment by rkhamis** [comment]
Okay, for the MVP, we'll do the basic plan. and once the capacity is consumed, we don't add more until the month is renewed

**Comment by xmonader** [comment]
closed in favor for #51
