### ISSUE TITLE
VDC information minio

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/vdc#54]
![image](https://user-images.githubusercontent.com/64129/101490016-6a706700-396a-11eb-905b-9c370767d10a.png)

- can have a nice description in the form saying these will be the credentials used to access the VDC's S3 
- let's rename minio to S3 in the chatflow

**Comment by waleedhammam** [comment]
https://github.com/threefoldtech/js-sdk/commit/c96c45e98306883a10cee5b607b2b396161a8e7f
