### ISSUE TITLE
System failed to deploy, but when restarted the chatflow can't use the same instance name

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/vdc#55]
Here it failed for some reason
![image](https://user-images.githubusercontent.com/64129/101490983-d0a9b980-396b-11eb-8305-447ae74649b9.png)

when I restarted the chatflow it says the name is already taken

![image](https://user-images.githubusercontent.com/64129/101490940-bd96e980-396b-11eb-84ff-7d4b8362b170.png)

**Comment by m-motawea** [comment]
we need to think about how to properly handle this. right now the sal ALWAYS reserves new capacity for a vdc using the provisioning wallet
but if the deployment failed, there is a very high chance that the capacity was reserved or part of it.

in that case we need to make the sal aware of the existing capacity for each pool and the required diff

**Comment by xmonader** [comment]
@m-motawea isn't it with the initialization wallet instead now?

**Comment by m-motawea** [comment]
each vdc is setup with a uuid in it's identitie's name and email. initial payment is done with an initialization wallet for 1 hour
