### ISSUE TITLE
VDC success page

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/vdc#60]
![image](https://user-images.githubusercontent.com/64129/101491724-c2a86880-396c-11eb-8ca4-1a0869c6785b.png)

- spacing is bit problematic

**Comment by waleedhammam** [comment]
![Uploading Screenshot from 2020-12-09 11-24-53.png…]()

**Comment by waleedhammam** [comment]
![Screenshot from 2020-12-09 11-24-53](https://user-images.githubusercontent.com/10658229/101611643-6f88f100-3a12-11eb-87b5-2a4dcfa87dc0.png)
