### ISSUE TITLE
VDC Dashboard: size should have unit

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/vdc#63]
![image](https://user-images.githubusercontent.com/64129/101493145-5169b500-396e-11eb-8a59-c538dd0eb94d.png)

Here it says 10, not clear 10 GB, 10TB, .. etc

**Comment by ranatrk** [comment]
According to [VM sizes map](https://github.com/threefoldfoundation/info_gridmanual/blob/development/src/smartcontract_for_it/capacity_kubernetes.md#vm-sizes) the size doesnt represent the disk size but represents multiple specs referenced as a VM size. This should be changed to show that for example size 1 is mapped to (vCpu =1, RAM (GiB)= 2, Storage (GiB)=50)
