### ISSUE TITLE
VDC Dashboard: S3 nodes have no details link

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/vdc#64]
![image](https://user-images.githubusercontent.com/64129/101493257-82e28080-396e-11eb-8200-ff0c51c90dec.png)

but for kubernetes tab there's 
![image](https://user-images.githubusercontent.com/64129/101493293-91309c80-396e-11eb-82ee-f2cc5a10a65f.png)

**Comment by ranatrk** [comment]
There is not much info to be displayed regarding the s3 zdbs. 
The only things saved are `size`, `wid`, `node_id`,  and `pool_id` and the workload itself doesnt contain extra information needed for example https://explorer.devnet.grid.tf/api/v1/reservations/workloads/7387.
