### ISSUE TITLE
VDC dashboard: kubernetes tab shows the private IPs in the table not the public ones

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/vdc#65]
![image](https://user-images.githubusercontent.com/64129/101493483-d0f78400-396e-11eb-9e8a-3ec69a1e6452.png)

IMO, we should only show the public ips in this view, and if someone wants the private IP they can go to the details popup

**Comment by ranatrk** [comment]
@xmonader this willl only be applicable for the master nodes, the worker nodes dont have a public ip

**Comment by ranatrk** [comment]
Changes:
![Screenshot from 2020-12-09 13-30-42](https://user-images.githubusercontent.com/17128393/101626357-86850e80-3a25-11eb-9689-037c47168e75.png)
